# Generated by Django 5.0.3 on 2024-03-28 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studentdata',
            new_name='data',
        ),
    ]
