# Generated by Django 5.0.3 on 2024-03-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_sample_data_delete_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sample_data',
            new_name='student_data',
        ),
    ]
